### ISSUE TITLE
Criação do diagrama de classes

### ISSUE THREAD

**Issue by felipeveigaramos** [felipeveigaramos/ES2_p4---cvlates#10]
Criação do diagrama de  classe --

**Comment by codingwithbatista** [comment]
há como adiar a elaboração da issue, @felipeveigaramos ?

**Comment by felipeveigaramos** [comment]
Entrega até dia 26.
Não esquece de mover o cartão para em progresso. @paulobcosta

**Comment by felipeveigaramos** [comment]
bom, como previamente discutido, foi adiado e já está entregue. os
tempos estão no arquivo na mesma pasta. Mito bom e obrigado.

closed.

2016-07-02 20:04 GMT-03:00, Paulo B. Costa notifications@github.com:

> Closed #10 via 2cd73934387903109f6b5e4886bf34e25be00aa5.
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/felipeveigaramos/ES2_p4---cvlates/issues/10#event-711289017

## 

```
            ***
```

"Numa toca no chão vivia um hobbit. Não uma toca desagradável, suja e
úmida, cheia de restos de minhocas e com
cheiro de lodo; tampouco uma toca seca, vazia e arenosa, sem nada em
que sentar ou o que comer: era a toca de um hobbit,
e isso quer dizer conforto. (...)"
(J.R.R.Tolkien - O Hobbit - PG#1)
