### ISSUE TITLE
Projetar o sistema: casos de uso

### ISSUE THREAD

**Issue by felipeveigaramos** [felipeveigaramos/ES2_p4---cvlates#3]
Projetar o sistema:
casos de uso

Criar os casos de uso, de forma textual e com diagramas que facilitem a comunicação com o programador.
Para a forma textual, pode-se usar o seguinte sistema:

Nome do caso de uso:
Atores: primário, secundário (usuário, sistema, por exemplo)
Pré-requisitos: pre-requisito1, pre-requisito2...
Fluxo:
1.O usuário clica em "testar".
1.1 Se aparecer a opção "indisponível", finaliza.
2. O usuário preenche o campo nome.
3.O sistema valida o nome.
4. O usuário preenche o campo idade.
5. ...
N. O usuário clica em ok.
<Qualquer fluxo alternativo segue aqui, se não pode ser coberto com o "i.1", "i.2"< etc>
<Estado final da aplicação após a execução, se aplicável,s egue aqui>

PS:Usecase acima meramente ilustrativo.

**Comment by codingwithbatista** [comment]
Obtive problemas quanto ao requisito funcional 3. A documentação simplesmente não especifica quais dados cadastrais a plataforma armazenará: Por exemplo, não se refere a armazenar dados acadêmicos e afins.

**Comment by felipeveigaramos** [comment]
@paulobcosta, considere os dados listados no rf1. entrada.

**Comment by felipeveigaramos** [comment]
pelo que vi, esse rf3 é só sobre edição especificamente  dos dados cadastrais, tem outros sobre inclusão de dados acadêmicos.

**Comment by codingwithbatista** [comment]
@felipeveigaramos ok, utilizei a entrada porém o caso a documentação não explica o cerne dos dados arquivados no perfil do cvlattes. Para contornar tal problemática estou referenciando o Lattes do governo federal. Isso será explicitado na elaboração  do diagrama de classes. Assim tento deixar a estruturação do projeto minimamente mais completa do que a documentação fornecida.

**Comment by codingwithbatista** [comment]
@felipeveigaramos commitado dentro do repositório, sujeito a análise e modificações.

**Comment by felipeveigaramos** [comment]
@paulobcosta  corrigidos alguns erros de ortografia,a crescentado .txt para verificação, removido caso 3.1 - não vamos alertar nada por e-mail.Gostaria que você verificasse pra mim: 

 1  verificar se  tá pedindo pra enviar o arquivo do documento - em um pounto você deixou possibilidade pra baixá-lo
2 verificar se escapou algum typo
3. deixar possibilidade pro  usuário excluir um documento também.
4. permitir edução em separado de dados cadastrais (cpf, e-mail e senha) dos institucionais.

(Edição\* problemas com meu teclado aqui)

**Comment by codingwithbatista** [comment]
@felipeveigaramos 3.1 - OK 
1. o arquivo a ser baixado não será enviado, entretanto o link deverá constar para baixar  (ieee, por exemplo) -- farei essa devida correção [Acredito que linkagem seria mais simples no processo de implementação]
2. Acredito que a questão de tipos estão bem definidas. Eles constarão de forma explícita no diagrama de classes (ao qual será realizado da forma textual, como citado pelo senhor)
3. Enquanto ao fato do usuário excluir, segui apenas a documentação. Entretanto, abrirei a possibilidade de exclusões para usuários logados.
4. Analisarei uma forma de deixar explícito o item 4 do comentário anterior.
Fazendo as correções agora
Uma dúvida ainda consta: Após a verificação por parte da gerência, quem fecha a issue? 
Att.

**Comment by felipeveigaramos** [comment]
pra facilitar e padronizar, pode deixar que eu fecho então. :)

obrigado pelas correções!
quanto ao que tinha citado, no item 2, seriam os erros acidentais mesmo, 
tinha uma ou duas coisas escrita com letras trocadas, ams acho que 
corrigi todas, só dá uma conferida pra mim.

Obrigado e parabéns: acho que ficou bem claro.
Para as classes, embora a edição seja feita em um crud principal, 
considere criar classes separadas na parte academica pra cada coisa.

[]s

Em 23/04/2016 13:51, Paulo B. Costa escreveu:

**Comment by codingwithbatista** [comment]
@felipeveigaramos Grato, realizei as devidas alterações para remoção de possíveis ambiguidades e salientando pontos importantes. Nas questões que ainda aparentarem ser demasiadamente abstratas no caso de uso, realizarei uma varredura para não sobrar duplo entendimento a partir do diagrama de classes.

**Comment by felipeveigaramos** [comment]
Perfeito. Vou fechar então o issue. Obrigado e parabéns pelo trabalho, @paulobcosta.

**Comment by felipeveigaramos** [comment]
PS: em tempo, não esqueça de fazer o diagrama de forma visual dos dois, quando terminar.

**Comment by codingwithbatista** [comment]
@felipeveigaramos os farei o quão breve possível =D
