### ISSUE TITLE
Definir modelo para o documento de requisitos

### ISSUE THREAD

**Issue by LuanBodner** [felipeveigaramos/ES2_p4---cvlates#5]
Criar um modelo que especifica as características de um documento de requisitos e os dados que deve apresentar.

**Comment by felipeveigaramos** [comment]
isso tecnicamente não precisava ser versionado, mas a cutucada foi 
recebida e anotada. :D

Desculpas pelo atraso. Até a aula vou ter algo pra apresentar.
[]s

Em 24/04/2016 18:17, LuanBodner escreveu:

**Comment by LuanBodner** [comment]
É que o professor precisa verificar que o tempo e tal, segundo ele precisa versionar sim.
Enfim, vou fazer isso agr :D

**Comment by felipeveigaramos** [comment]
tão tá.
vou fazer amanhã, de alguma forma.

Em 24/04/2016 18:21, LuanBodner escreveu:

**Comment by felipeveigaramos** [comment]
Luan,s eguinte.
Estive lendo seu modelo e perguntando umas coisas pro ré e acho qeu
vocÊ vai ter que dar uma revisada:
aquilo é pra ser o modelo, não uma descrição. Explico:
você não vai por seu nome como autor, um título de documento e tals.
aquilo é como se fosse o modeo mesmo que deveria ser preenchido.
claro, com explciações no que for necessário.

Mas não esqueça de colocar informações, quase que um cabeçalho mesmo,
sobre data, versão do documento, essas coisas. enfim, é como um modelo
rpa ser preenchido.

2016-04-26 13:10 GMT-03:00, LuanBodner notifications@github.com:

> Closed #5.
> 
> ---
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/felipeveigaramos/ES2_p4---cvlates/issues/5#event-641715630

## 

```
            ***
```

"Numa toca no chão vivia um hobbit. Não uma toca desagradável, suja e
úmida, cheia de restos de minhocas e com
cheiro de lodo; tampouco uma toca seca, vazia e arenosa, sem nada em
que sentar ou o que comer: era a toca de um hobbit,
e isso quer dizer conforto. (...)"
(J.R.R.Tolkien - O Hobbit - PG#1)
